apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myflaskapp
  template:
    metadata:
      labels:
        app: myflaskapp
    spec:
      containers:
        - name: myflaskapp
          image: acrvinaymultiregion01.azurecr.io/random-api:v1
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: myflaskapp-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # 🔒 INTERNAL LB
spec:
  type: LoadBalancer
  selector:
    app: myflaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
